tasks:
  default:
    onboard_world: MessengerBotChatOnboardWorld
    task_world: MessengerBotChatTaskWorld
    timeout: 1800
    agents_required: 1
task_name: chatbot
world_module: parlai.chat_service.tasks.chatbot.worlds
overworld: MessengerOverworld
max_workers: 30
opt:
  debug: True
  models:
    bb3_3B:
      model: transformer/generator
      model_file: zoo:bb3/bb3_3B/model
      interactive_mode: True
      no_cuda: False
      opt: gen/r2c2_bb3
      search-server: 0.0.0.0:8080
additional_args:
  page_id: 1 # Configure Your Own Page
